### ISSUE TITLE
Tip calculator

### ISSUE THREAD

**Issue by Riley19280** [WesR/ITSC-1212#1]
there are too many basic comments

**Comment by WesR** [comment]
Yeah :( We are supposed to comment more then this too.

**Comment by Riley19280** [comment]
geez. thats crazy.i couldnt imagine. like reading that code is like reading a book. theres nothing complicated

**Comment by WesR** [comment]
[CommentingSample.txt](https://github.com/WesR/ITSC-1212/files/464700/CommentingSample.txt)
This was the example we were given.

**Comment by WesR** [comment]
Theres more writeup then code!

**Comment by Riley19280** [comment]
you literally just made it harder to read the code!

**Comment by WesR** [comment]
That's what  say. Maybe it was just to show all that you _can_ do, not all you should. Any programmer should be able to understand what a print statement is.
